const nereusDocIds = [
  'overview/why-nereus',
  'overview/architecture',
  'overview/reading-guide',
  'concepts/stream-record-entry-offset',
  'concepts/protocol-logical-physical-coordinates',
  'concepts/primary-wal',
  'concepts/stream-head-and-commit-chain',
  'concepts/cas-and-linearization-point',
  'concepts/read-target-and-offset-index',
  'data-paths/append-flow',
  'data-paths/append-outcomes',
  'data-paths/append-recovery',
  'data-paths/read-flow',
  'data-paths/read-boundaries',
  'data-paths/index-repair-and-fallback',
  'storage/storage-profiles',
  'storage/object-wal',
  'storage/bookkeeper-wal',
  'storage/generation-overview',
  'storage/generation-lifecycle',
  'storage/generation-selection-and-fallback',
  'storage/materialization',
  'integrations/pulsar',
  'integrations/pulsar-cursor-and-subscription',
  'integrations/native-kafka',
  'integrations/kafka-produce-and-fetch',
  'integrations/kafka-recovery-and-compaction',
  'integrations/kop-vs-native-kafka',
  'operations/retention-and-gc',
  'operations/object-gc-state-machine',
  'operations/bookkeeper-retention',
  'operations/failure-and-recovery',
  'operations/backpressure-and-timeouts',
  'operations/observability',
  'operations/security-and-multitenancy',
  'examples/pulsar-object-wal-sync',
  'examples/pulsar-bookkeeper-async-object',
  'examples/bookkeeper-sync-object-timeout',
  'examples/kafka-transaction-and-delete-records',
  'development/module-boundaries',
  'development/source-reading-map',
  'development/project-status',
  'reference/correctness-authorities',
  'reference/non-goals',
  'reference/glossary',
  'reference/state-machines',
  'reference/end-to-end-cheatsheet',
  'reference/document-baseline',
] as const;

export const legacyDocRedirects = [
  {
    from: '/docs/category/overview/',
    to: '/docs/nereus/category/overview/',
  },
  ...nereusDocIds.map((id) => ({
    from: `/docs/${id}/`,
    to: `/docs/nereus/${id}/`,
  })),
];
